from nvcr.io/nvidia/pytorch:22.02-py3

COPY artifact/setup/requirements.txt /opt/app/requirements.txt

WORKDIR /opt/app

RUN pip install -r requirements.txt 

RUN wget -q https://pmb.let.rug.nl/releases/pmb-2.1.0.zip && -wget -q https://raw.githubusercontent.com/RikVN/DRS_parsing/abdf25563d74e70bf0fae28149a2755921e6b111/evaluation/clf_signature.yaml

WORKDIR /workspace